### PR TITLE
Finalize recipe (+ test new rclone copy stage)

### PR DESCRIPTION
**Pull request by jbusecke**
This seems like a pretty simple recipe, but running it locally on the hub with 

```
mamba create -n runner0102 python=3.11 -y
conda activate runner0102
pip install pangeo-forge-runner==0.10.2 --no-cache-dir
```

```
pangeo-forge-runner bake \
  --repo=./ \
  --Bake.recipe_id=chirps-global-daily\
  -f configs/config_local_hub.py
```

Blows out the 128GB of memory! The files are extremely compressed, but should still fit into memory (1GB on disk, ~20GB in memory x2 files). This smells like the same issue we (@norlandrhagen) had with fsspec balloning the memory for older recipes and virtualizarr generation? What is going on here...

### CODE REVIEW

**Comment by jbusecke** [comment]
Oh I did not set the `target_chunks`

**Comment by jbusecke** [comment]
Ok nice, this is working locally. 

Running a test on dataflow now.

**Comment by jbusecke** [comment]
Ok that works out fine. @ks905383 can you check out the test dataset?

You can run this on the leap hub
```python
import xarray as xr
xr.open_dataset("gs://leap-scratch/data-library/feedstocks/chirps_feedstock/chirps-global-daily.zarr", engine='zarr', chunks={})
```

**Comment by ks905383** [comment]
Nice, seems to work for 1981-1982 (and I see you've staged the recipe for the whole timeframe)

**Comment by jbusecke** [comment]
@ks905383 awesome. I would love to see what sort of processing you apply to the data, so we can prototype that. If you think that should rather be applied afterwards we can get this finalized.

**Comment by jbusecke** [comment]
I have rebased this on https://github.com/leap-stc/leap-data-management-utils/pull/60 and will see if the copy stage works (moving it to `m2lines-testing` like in https://github.com/leap-stc/test-transfer) before merging and processing the entire thing.
- [ ] Redirect to proper OSN bucket
- [ ] Update secrets in manager to fit bucket

**Comment by jbusecke** [comment]
Ayyyy this worked apparently. Need to run for dinner, but will test output tomorrow! Exciting.

**Comment by jbusecke** [comment]
Was able to [confirm](https://github.com/leap-stc/leap-data-management-utils/pull/60#issuecomment-2438057541) that the transfer works. Lets change the target bucket/creds and then ingest the entire recipe over at https://github.com/leap-stc/leap-data-management-utils/pull/60

**Comment by jbusecke** [comment]
There is still a bit of a smell here since I have to define the target bucket+path in the recipe and the creds are hardcoded here. @norlandrhagen do you have opinions on how to reconcile this?

**Comment by jbusecke** [comment]
This should be all set, but it seems the original server is down at the moment. 

cc @ks905383

**Comment by norlandrhagen** [comment]
For this bit?

```python
| CopyRclone(target=catalog_store_urls["chirps-global-daily"].replace("https://nyu1.osn.mghpcc.org/","")) #FIXME`
```

Maybe we can separate the prefix from the bucket/path with some `leap_data_management_utils` help?

**Comment by jbusecke** [comment]
@norlandrhagen 👍 i think we could possibly do this as a clean up sprint where we reduce the amount of manuall entered (and highly interdependent) naming entries for the user?

**Comment by jbusecke** [comment]
I guess we were hammering the storage at a rate that is not allowed? See https://cloud.google.com/storage/docs/gcs429
image

I thought this was the cloud! Hahaha.

**Comment by jbusecke** [comment]
This is pretty odd. We also specify max-workers as 50 and it seemed to have scaled beyond that?

**Comment by jbusecke** [comment]
And I guess max-workers is useless when using dataflow prime.

**Comment by jbusecke** [comment]
Ill try one more time with even less workers and larger chunks (hopefully resulting in less writes?), but I wonder if we could address this more generally by creating an 'empty directory structure' before writing out the chunks. This seems to be what people suggest [here](https://stackoverflow.com/a/32150168) and [here](https://stackoverflow.com/questions/31851192/rate-limit-with-apache-spark-gcs-connector/31955475#31955475)

**Comment by jbusecke** [comment]
ughhhh its scaling past the limit I set again... is this a bug in runner?

**Comment by jbusecke** [comment]
Ill have to look into this more next week. Will have to turn to some other things now.

**Comment by jbusecke** [comment]
Its stuck again...god I am sooo tired of this fsspec bug

**Comment by jbusecke** [comment]
Trying Nathans patch fix now.

**Comment by jbusecke** [comment]
So far so good...

**Comment by jbusecke** [comment]
Taking too long, lets try some more workers

**Comment by norlandrhagen** [comment]
As of this commit, this recipe worked. A few notes:
- I bumped back gcsfs to an arbitrary release in feb which fixed the `Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.` error
- I ran with the hub config with no issues. On the 512GB ram instance, it ran in a few minutes on the direct runner.

```python
import xarray as xr 
store = 'https://nyu1.osn.mghpcc.org/leap-pangeo-pipeline/chirps_feedstock/chirps-global-daily.zarr'
ds = xr.open_dataset(store, engine='zarr', chunks={})
````

```

<xarray.Dataset> Size: 922GB
Dimensions:    (latitude: 2000, longitude: 7200, time: 16010)
Coordinates:
  * latitude   (latitude) float32 8kB -49.97 -49.92 -49.88 ... 49.87 49.92 49.97
  * longitude  (longitude) float32 29kB -180.0 -179.9 -179.9 ... 179.9 180.0
  * time       (time) datetime64[ns] 128kB 1981-01-01 1981-01-02 ... 2024-10-31
Data variables:
    precip     (time, latitude, longitude) float32 922GB dask.array<chunksize=(200, 200, 720), meta=np.ndarray>
```

**Comment by norlandrhagen** [comment]
Merging this into main for now. We had to run this on the jupyter-hub instead of dataflow to avoid this:

https://github.com/leap-stc/chirps_feedstock/issues/3

**Pull request merged**
